### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by supersonicBlonde** [jweir/colorwheel#24]
I have this error 

Uncaught TypeError: Cannot read property 'x' of undefined

How to solve it

**Comment by jweir** [comment]
Howdy – 

Without an example of code I can not debug this or give you any direction.  Is there a URL with the code? Or maybe you can paste your code into a gist https://gist.github.com

**Comment by vinimendes3** [comment]
Same problem here

**Comment by vinimendes3** [comment]
TypeError: Cannot read property 'x' of undefined
    at Function.R._engine.create (http://localhost:8100/lib/raphael/raphael.js:6977:20)
    at R (http://localhost:8100/lib/raphael/raphael.js:464:47)
    at create (http://localhost:8100/lib/colorwheel/colorwheel.js:46:16)
    at Function.Raphael.colorwheel (http://localhost:8100/lib/colorwheel/colorwheel.js:341:10)

**Comment by jweir** [comment]
Which version of Raphael are you using?
